# Generated by Django 3.2.8 on 2021-10-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trick_or_treating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
